'''
This file contains relevant name changes in order to merge the FBref and FPL player databases
'''
NAME_CHANGES = {
    'Adrián': 'Adrián San Miguel del Castillo',
    'Semi Ajayi': 'Oluwasemilogo Adesewo Ibidapo Ajayi',
    'Thiago Alcántara': 'Thiago Alcántara do Nascimento',
    'Alisson': 'Alisson Ramses Becker',
    'Allan': 'Allan Marques Loureiro',
    'Dele Alli': 'Bamidele Alli',
    'Felipe Anderson': 'Felipe Anderson Pereira Gomes',
    'Jóhann Berg Guðmundsson': 'Johann Berg Gudmundsson',
    'Bernard': 'Bernard Anício Caldeira Duarte',
    'Bernardo': 'Bernardo Fernandes da Silva Junior',
    'João Cancelo': 'João Pedro Cavaco Cancelo',
    'Ian Carlo Poveda':'Ian Carlo Poveda-Ocampo',
    'Matty Cash': 'Matthew Cash',
    'Ivan Cavaleiro': 'Ivan Ricardo Neves Abreu Cavaleiro',
    'Dani Ceballos': 'Daniel Ceballos Fernández',
    'Ben Chilwell': 'Benjamin Chilwell',
    'Séamus Coleman': 'Seamus Coleman',
    'Hélder Costa': 'Hélder Wander Sousa de Azevedo e Costa',
    'Vladimír Coufal': 'Vladimir Coufal',
    'Rúben Dias': 'Rúben Santos Gato Alves Dias',
    'Gabriel Dos Santos': 'Gabriel Magalhães',
    'Ederson': 'Ederson Santana de Moraes',
    'Ahmed Elmohamady': 'Ahmed El Mohamady',
    'Mohamed Elneny': 'Mohamed Naser El Sayed Elneny',
    'Łukasz Fabiański': 'Lukasz Fabianski',
    'Fabinho': 'Fabio Henrique Tavares',
    'Bruno Fernandes': 'Bruno Miguel Borges Fernandes',
    'Fred': 'Frederico Rodrigues de Paula Santos',
    'Fernandinho': 'Fernando Luiz Rosa',
    'Eric García': 'Eric Garcia',
    'André Gomes': 'André Filipe Tavares Gomes',
    'Joe Gomez': 'Joseph Gomez',
    'Pablo Hernández': 'Pablo Hernández Domínguez',
    'Son Heung-min': 'Heung-Min Son',
    'Pierre Højbjerg': 'Pierre-Emile Højbjerg',
    'Gabriel Jesus': 'Gabriel Fernando de Jesus',
    'Joelinton': 'Joelinton Cássio Apolinário de Lira',
    'Jorginho': 'Jorge Luiz Frello Filho',
    'Naby Keïta': 'Naby Keita',
    'Sead Kolašinac': 'Sead Kolasinac',
    'Ezri Konsa': 'Ezri Konsa Ngoyo',
    'Mateo Kovačić': 'Mateo Kovacic',
    'Filip Krovinović': 'Filip Krovinovic',
    'Érik Lamela': 'Erik Lamela',
    'David Luiz': 'David Luiz Moreira Marinho',
    'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
    'Solly March': 'Solomon March',
    'Gabriel Martinelli': 'Gabriel Teodoro Martinelli Silva',
    'Nemanja Matić': 'Nemanja Matic',
    'Joël Matip': 'Joel Matip',
    'Luka Milivojević': 'Luka Milivojevic',
    'Lucas Moura': 'Lucas Rodrigues Moura da Silva',
    'João Moutinho': 'João Filipe Iria Santos Moutinho',
    'Pedro Neto': 'Pedro Lomba Neto',
    'Rúben Neves': 'Rúben Diogo da Silva Neves',
    'Eddie Nketiah': 'Edward Nketiah',
    'Rui Patrício': 'Rui Pedro dos Santos Patrício',
    'Daniel Podence': 'Daniel Castelo Podence',
    'Richarlison': 'Richarlison de Andrade',
    'Bobby Reid': 'Bobby Decordova-Reid',
    'Jaïro Riedewald': 'Jairo Riedewald',
    'Rodri': 'Rodrigo Hernandez',
    'Rodrigo': 'Rodrigo Moreno',
    'Oriol Romeu': 'Oriol Romeu Vidal',
    'Nélson Semedo': 'Nélson Cabral Semedo',
    'Gylfi Sigurðsson': 'Gylfi Sigurdsson',
    'Bernardo Silva': 'Bernardo Mota Veiga de Carvalho e Silva',
    'Fábio Silva': 'Fabio Silva',
    'Thiago Silva': 'Thiago Thiago',
    'Tomáš Souček': 'Tomas Soucek',
    'Çağlar Söyüncü': 'Çaglar Söyüncü',
    'Ferrán Torres': 'Ferran Torres',
    'Trézéguet': 'Mahmoud Ahmed Ibrahim Hassan',
    'Rúben Vinagre': 'Rúben Gonçalo Silva Nascimento Vinagre',
    'Vitinha': 'Vitor Ferreira',
    'Matěj Vydra': 'Matej Vydra',
    'Willian': 'Willian Borges Da Silva',
    'Andre-Frank Zambo Anguissa': 'André-Frank Zambo Anguissa'
}