'''
This file contains relevant name changes in order to merge the FBref and FPL player databases
'''
NAME_CHANGES = {
    'Max Aarons': 'Maximillian Aarons',
    'Adrián': 'Adrián San Miguel del Castillo',
    'Semi Ajayi': 'Oluwasemilogo Adesewo Ibidapo Ajayi',
    'Thiago Alcántara': 'Thiago Alcántara do Nascimento',
    'Alisson': 'Alisson Ramses Becker',
    'Allan': 'Allan Marques Loureiro',
    'Dele Alli': 'Bamidele Alli',
    'Felipe Anderson': 'Felipe Anderson Pereira Gomes',
    'Angeliño': 'José Ángel Esmorís Tasende',
    'Marko Arnautović': 'Marko Arnautovic',
    'Borja Bastón': 'Borja González Tomás',
    'Asmir Begović': 'Asmir Begovic',
    'Jóhann Berg Guðmundsson': 'Johann Berg Gudmundsson',
    'Bernard': 'Bernard Anício Caldeira Duarte',
    'Bernardo': 'Bernardo Fernandes da Silva Junior',
    'Muhamed Bešić': 'Muhamed Besic',
    'Léo Bonatini': 'Bonatini Lohner Maia Bonatini',
    'Izzy Brown': 'Isaiah Brown',
    'Bruno': 'Bruno Saltor Grau',
    'Emi Buendía': 'Emiliano Buendía',
    'João Cancelo': 'João Pedro Cavaco Cancelo',
    'Étienne Capoue': 'Etienne Capoue',
    'Ian Carlo Poveda':'Ian Carlo Poveda-Ocampo',
    'Matty Cash': 'Matthew Cash',
    'Jonny Castro': 'Jonathan Castro Otto',
    'Ivan Cavaleiro': 'Ivan Ricardo Neves Abreu Cavaleiro',
    'Dani Ceballos': 'Daniel Ceballos Fernández',
    'Petr Čech': 'Petr Cech',
    'Ben Chilwell': 'Benjamin Chilwell',
    'Lee Chung-yong': 'Chung-yong Lee',
    'Séamus Coleman': 'Seamus Coleman',
    'Hélder Costa': 'Hélder Wander Sousa de Azevedo e Costa',
    'Vladimír Coufal': 'Vladimir Coufal',
    'Greg Cunningham': 'Greg Cunninghamm',
    'Matty Daly': 'Matthew Daly',
    'Danilo': 'Danilo Luiz da Silva',
    'Diogo Dalot': 'José Diogo Dalot Teixeira',
    'David De Gea': 'David de Gea',
    'Rúben Dias': 'Rúben Santos Gato Alves Dias',
    'Brahim Díaz': 'Brahim Diaz',
    'Gabriel Dos Santos': 'Gabriel Magalhães',
    'Thomas Doyle': 'Tommy Doyle',
    'Aleksandar Dragović': 'Aleksandar Dragovic',
    'Danny Drinkwater': 'Daniel Drinkwater',
    'Josip Drmić': 'Josip Drmic',
    'Martin Dúbravka': 'Martin Dubravka',
    'Ederson': 'Ederson Santana de Moraes',
    'Tom Edwards': 'Thomas Edwards',
    'Harvey Elliot': 'Harvey Elliott',
    'Rob Elliot': 'Robert Elliot',
    'Ahmed Elmohamady': 'Ahmed El Mohamady',
    'Mohamed Elneny': 'Mohamed Naser El Sayed Elneny',
    'Björn Engels': 'Bjorn Engels',
    'Łukasz Fabiański': 'Lukasz Fabianski',
    'Fabinho': 'Fabio Henrique Tavares',
    'Fabricio': 'Fabricio Agosto Ramírez',
    'Ralf Fährmann': 'Ralf Fahrmann',
    'Bruno Fernandes': 'Bruno Miguel Borges Fernandes',
    'Gedson Fernandes': 'Gedson Carvalho Fernandes',
    'Kiko Femenía': 'Francisco Femenía Far',
    'Fred': 'Frederico Rodrigues de Paula Santos',
    'Fernandinho': 'Fernando Luiz Rosa',
    'José Fonte': 'Jose Fonte',
    'Jesús Gámez': 'Jesús Gámez Duarte',
    'Idrissa Gana Gueye': 'Idrissa Gueye',
    'Eric García': 'Eric Garcia',
    'André Gomes': 'André Filipe Tavares Gomes',
    'Joe Gomez': 'Joseph Gomez',
    'Jon Gorenc Stanković': 'Jon Gorenc Stankovic',
    'Arnaut Groeneveld': 'Arnaut Danjuma Groeneveld',
    'Marko Grujić': 'Marko Grujic',
    'Mattéo Guendouzi': 'Matteo Guendouzi',
    'İlkay Gündoğan': 'Ilkay Gündogan',
    'Frederic Guilbert': 'Frédéric Guilbert',
    'Massadio Haïdara': 'Massadio Haidara',
    'Ahmed Hegazi': 'Ahmed El-Sayed Hegazi',
    'Javier Hernández': 'Javier Hernández Balcázar',
    'Pablo Hernández': 'Pablo Hernández Domínguez',
    'Son Heung-min': 'Heung-Min Son',
    'Junior Hoilett': 'David Junior Hoilett',
    'Pierre Højbjerg': 'Pierre-Emile Højbjerg',
    'Zlatan Ibrahimović': 'Zlatan Ibrahimovic',
    'José Izquierdo': 'José Heriberto Izquierdo Mena',
    'Eldin Jakupović': 'Eldin Jakupovic',
    'Jesé': 'Jesé Rodríguez Ruiz',
    'Gabriel Jesus': 'Gabriel Fernando de Jesus',
    'Joelinton': 'Joelinton Cássio Apolinário de Lira',
    'Bruno Jordão': 'Bruno André Cavaco Jordao',
    'Jorginho': 'Jorge Luiz Frello Filho',
    'Joselu': 'Jose Luis Mato Sanmartín',
    'Mathias Jørgensen': 'Mathias Jorgensen',
    'Jota': 'José Ignacio Peleteiro Romallo',
    'Younès Kaboul': 'Younes Kaboul',
    'Naby Keïta': 'Naby Keita',
    'Kenedy': 'Robert Kenedy Nunes do Nascimento',
    'Sead Kolašinac': 'Sead Kolasinac',
    'Ezri Konsa': 'Ezri Konsa Ngoyo',
    'Mateo Kovačić': 'Mateo Kovacic',
    'Bojan Krkić': 'Bojan Krkic Perez',
    'Filip Krovinović': 'Filip Krovinovic',
    'Freddie Ladapo': 'Olayinka Fredrick Oladotun Ladapo',
    'Érik Lamela': 'Erik Lamela',
    'David Luiz': 'David Luiz Moreira Marinho',
    'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
    'Solly March': 'Solomon March',
    'João Mário': 'João Mário Naval Costa Eduardo',
    'Lazar Marković': 'Lazar Markovic',
    'Martinelli': 'Gabriel Teodoro Martinelli Silva',
    'Gabriel Martinelli': 'Gabriel Teodoro Martinelli Silva',
    'Nemanja Matić': 'Nemanja Matic',
    'Joël Matip': 'Joel Matip',
    'Luka Milivojević': 'Luka Milivojevic',
    'Aleksandar Mitrović': 'Aleksandar Mitrovic',
    'Steve Mounié': 'Steve Mounie',
    'Lucas Moura': 'Lucas Rodrigues Moura da Silva',
    'João Moutinho': 'João Filipe Iria Santos Moutinho',
    'Charly Musonda Jr.': 'Charly Musonda',
    'Yoshinori Mutō': 'Yoshinori Muto',
    'Badou Ndiaye': 'Papa Alioune Ndiaye',
    'Pedro Neto': 'Pedro Lomba Neto',
    'Rúben Neves': 'Rúben Diogo da Silva Neves',
    'Eddie Nketiah': 'Edward Nketiah',
    "Georges-Kévin N'Koudou": 'Georges-Kévin Nkoudou',
    'Allan Nyom': 'Allan-Roméo Nyom',
    'Emerson Palmieri': 'Emerson Palmieri dos Santos',
    'Rui Patrício': 'Rui Pedro dos Santos Patrício',
    'Pedro': 'Pedro Rodríguez Ledesma',
    'João Pedro': 'João Pedro Junqueira de Jesus',
    'Ricardo Pereira': 'Ricardo Domingos Barbosa Pereira',
    'Daniel Podence': 'Daniel Castelo Podence',
    'Àngel Rangel': 'Angel Rangel',
    'Kayne Ramsey': 'Kayne Ramsay',
    'Jazz Richards': 'Ashley Darel Jazz Richards',
    'Richarlison': 'Richarlison de Andrade',
    'Bobby Reid': 'Bobby Decordova-Reid',
    'Pepe Reina': 'José Reina',
    'Jaïro Riedewald': 'Jairo Riedewald',
    'Roberto': 'Roberto Jimenez Gago',
    'Rodri': 'Rodrigo Hernandez',
    'Rodrigo': 'Rodrigo Moreno',
    'Oriol Romeu': 'Oriol Romeu Vidal',
    'Ismaila Sarr': 'Ismaïla Sarr',
    'Jean Seri': 'Jean Michael Seri',
    'Nélson Semedo': 'Nélson Cabral Semedo',
    'Gylfi Sigurðsson': 'Gylfi Sigurdsson',
    'Adrien Silva': 'Adrien Sebastian Perruchet Silva',
    'Bernardo Silva': 'Bernardo Mota Veiga de Carvalho e Silva',
    'Fábio Silva': 'Fabio Silva',
    'Thiago Silva': 'Thiago Thiago',
    'Xande Silva': 'Alexandre Nascimento Costa Silva',
    'Josh Sims': 'Joshua Sims',
    'Emile Smith-Rowe': 'Emile Smith Rowe',
    'Tomáš Souček': 'Tomas Soucek',
    'Çağlar Söyüncü': 'Çaglar Söyüncü',
    'Julián Speroni': 'Julian Speroni',
    'Kostas Stafylidis': 'Konstantinos Stafylidis',
    'Isaac Success': 'Isaac Success Ajayi',
    'Ki Sung-yueng': 'Sung-yueng Ki',
    'Lasse Sørensen': 'Lasse Sorenson',
    'Dušan Tadić': 'Dusan Tadic',
    'Ferrán Torres': 'Ferran Torres',
    'Yaya Touré': 'Gnegneri Yaya Touré',
    'Trézéguet': 'Mahmoud Ahmed Ibrahim Hassan',
    'Jesús Vallejo': 'Jesús Vallejo Lázaro',
    'Rúben Vinagre': 'Rúben Gonçalo Silva Nascimento Vinagre',
    'Vitinha': 'Vitor Ferreira',
    'Nikola Vlašić': 'Nikola Vlasic',
    'Mario Vrančić': 'Mario Vrancic',
    'Matěj Vydra': 'Matej Vydra',
    'Willian': 'Willian Borges Da Silva',
    'Joe Willock': 'Joseph Willock',
    'Andre-Frank Zambo Anguissa': 'André-Frank Zambo Anguissa',
    'Richairo Živković': 'Richairo Zivkovic'
}